dotnetCoreProject/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetCoreProject.Controllers.infrastructure;
using dotnetCoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace dotnetCoreProject.Controllers
{
    public class PagesController : Controller
    {

        private readonly shoppingDbContext context;

        public PagesController(shoppingDbContext context)
        {
            this.context = context;
        }


        public async Task<IActionResult> Page(string slug)
        {

            if(slug == null)
            {
                return View(await context.pages.FirstOrDefaultAsync(x => x.slug == "home"));
            }

            Page page = await context.pages.FirstOrDefaultAsync(x => x.slug == slug);
            if(page == null)
            {
                return NotFound();
            }


            return View(page);


        }
    }
}

dotnetCoreProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetCoreProject.Controllers.infrastructure;
using dotnetCoreProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace dotnetCoreProject.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {

        private readonly shoppingDbContext context;

        public ProductController(shoppingDbContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index(int p = 1)
        {
            int pageSize = 6;
            var products = await context.products.OrderBy(x => x.Id).Include(x=> x.category)
                .Skip((p-1)*pageSize).Take(pageSize).ToListAsync();


            ViewBag.PageNumber = p;
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)(context.products.Count()*1.0 / pageSize));
            ViewBag.range = pageSize;


            return View(products);

        }



        // get product/productByCategory

        public async Task<IActionResult> productByCategory(string catgorySlug , int p = 1)
        {

            Category category = await context.categories.Where(x => x.slug == catgorySlug).FirstOrDefaultAsync();

            if (category == null) return RedirectToAction("Index");

            int pageSize = 6;

            var products = await context.products.Where(x => x.CategoryId == category.id)
                .OrderBy(x => x.Id).Include(x=> x.category).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync();

            ViewBag.category = category.name;
            ViewBag.slug = catgorySlug;
            ViewBag.PageNumber = p;
            
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)(context.products.Where(x=> x.CategoryId == category.id).Count()*1.0 / pageSize));
            ViewBag.PageRange = pageSize;


            return View(products);


        }

    }
}

dotnetCoreProject/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">Pages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-area="Admin" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Roles" asp-area="Admin" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item logout">
                            <a asp-area="" asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

dotnetCoreProject/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if(TempData["success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["success"]
    </div>
}

@if(TempData["error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["error"];
    </div>
}