dotnetCoreProject/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dotnetCoreProject.Controllers.infrastructure;
using dotnetCoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace dotnetCoreProject.Controllers
{
    public class PagesController : Controller
    {

        private readonly shoppingDbContext context;

        public PagesController(shoppingDbContext context)
        {
            this.context = context;
        }


        public async Task<IActionResult> Page(string slug)
        {

            if(slug == null)
            {
                return View(await context.pages.FirstOrDefaultAsync(x => x.slug == "home"));
            }

            Page page = await context.pages.FirstOrDefaultAsync(x => x.slug == slug);
            if(page == null)
            {
                return NotFound();
            }


            return View(page);


        }
    }
}

dotnetCoreProject/Controllers/infrastructure/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotnetCoreProject.Controllers.infrastructure
{
    public class CategoriesViewComponent : ViewComponent
    {

        private readonly shoppingDbContext context;

        public CategoriesViewComponent(shoppingDbContext context)
        {
            this.context = context;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await context.categories.OrderBy(x => x.sorting).ToListAsync();
            
            return View(categories);
        }


    }
}

dotnetCoreProject/Controllers/infrastructure/MainMenuViewComponent.cs
using dotnetCoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotnetCoreProject.Controllers.infrastructure
{
    public class MainMenuViewComponent : ViewComponent
    {

        private readonly shoppingDbContext context;

        public MainMenuViewComponent(shoppingDbContext context)
        {
            this.context = context;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var pages = await context.pages.OrderBy(x => x.sorting).ToListAsync();

            return View(pages);
        }


    }
}

dotnetCoreProject/Controllers/infrastructure/SmallCartViewComponent.cs
using dotnetCoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dotnetCoreProject.Controllers.infrastructure
{
    public class SmallCartViewComponent:ViewComponent
    {

        //private readonly shoppingDbContext context;

        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.getJson<List<CartItem>>("cart");
            SmallCartViewModel smallCartView;

            if(cart == null || cart.Count == 0)
            {
                smallCartView = null;
            }
            else
            {
                smallCartView = new SmallCartViewModel
                {
                    totalItems = cart.Sum(x => x.quantity),
                    quntity = cart.Sum(x => x.quantity * x.total)
                };
            }

            return View(smallCartView);

        }



    }
}

dotnetCoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnetCoreProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotnetCoreProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-row-1 justify-content-end">
                        
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">hi, @User.Identity.Name, logout</a>
                            </li>
                            <li class="nav-item ml-1">

                                <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">My Account</a>

                            </li>

                            @if(User.IsInRole("Admin") || User.IsInRole("Editor"))
                            {
                                <li class="nav-item ml-1">
                                    <a asp-area="Admin" asp-controller="Pages" asp-action="Index" class="btn btn-success">Admin Area</a>
                                </li>
                            }

                        }
                        else
                        {
                        <li class="nav-item mr-2">
                            <a asp-controller="Account" asp-action="Login" class="btn btn-success">Login</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                        </li>

                        

                        }

                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @await Component.InvokeAsync("MainMenu")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            <div class="row">

                <div class="col-md-3">
                    @await Component.InvokeAsync("Categories")

                    <div class="smallCart bg-success text-white p-2 mt-3">
                        @await Component.InvokeAsync("SmallCart")
                    </div>

                </div>
                <div class="col">

                    @RenderBody()
                </div>

            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - dotnetCoreProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

dotnetCoreProject/Views/Shared/_notificationPartial.cshtml
@if(TempData["success"]! != null)
{
    <div class="alert alert-success notification">
        @TempData["success"]
    </div>
}

@if (TempData["error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["error"]
    </div>
}